"use client";
import { Metadata, NavBar, Footer, Provider, store, ThemeProvider, CacheProvider, createCache, createTheme, LoadingSpinner, useState } from "./app.modules";
import { Inter } from "next/font/google";
import "@/assets/globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Brand | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const cache = createCache({ key: "css", prepend: true });
  const theme = createTheme();

  const toggleDrawer = () => {
    setIsDrawerOpen(!isDrawerOpen);
  };

  return (
    <html lang="en">
      <Provider store={store}>
        <CacheProvider value={cache}>
          <ThemeProvider theme={theme}>
            <body className={inter.className}>
              <LoadingSpinner>
                <>
                  <NavBar
                    toggleDrawer={toggleDrawer}
                    isDrawerOpen={isDrawerOpen}
                  />
                  {children}
                  <Footer />
                </>
              </LoadingSpinner>
            </body>
          </ThemeProvider>
        </CacheProvider>
      </Provider>
    </html>
  );
}
